name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change to your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key
        chmod 600 private_key  # Set correct permissions
        ls
        

    - name: Deploy to EC2
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key $EC2_USER@$EC2_HOST
        ls
        source myenv/bin/activate 
        streamlit run fast_api_app/streamlit_app.py --server.port 8502 --server.address 0.0.0.0
